Repository AICoE/sesheta, pull requests merged in 2019-05, with the labels that each got.

#4 relocked to address CVE-2019-11324 and CVE-2018-18074
  Pipfile.lock
Labels: bot, human_intervention_required

#8 fixes for using config json from configmap and deployment templates
  check_if_labels_present.py
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/deployment-template.yaml
Labels: approved

#7 Usefull anisble playbooks for faster deployment
  README.md
  playbooks/deprovision.yaml
  playbooks/provision.yaml
Labels: approved

#5 minor fix to update the deprecated attribute
  pyproject.toml
Labels: approved

#6 migrated sesheta approver bot from core/bots
  approver.py
  openshift/cronJob-template.yaml
  sesheta/common.py
Labels: approved, bot

#10 minor fix to make sesheta approver work with zuul ci
  approver.py
  openshift/cronJob-template.yaml
  sesheta/common.py
Labels: approved

#13 Updated config json for thoth-station
  config.json
Labels: approved

#9 fix scrum bot to point correct scrum time
  openshift/cronJob-template.yaml
Labels: approved

#11 maintain consistency as sesheta
  sesheta/__init__.py
Labels: approved

#15 wrong switch between secret and token
  sesheta/webhook_processors/github_reviews.py
  sesheta/webhooks.py
Labels: approved
