Repository AICoE/sesheta, pull requests merged in 2020-05, with the labels that each got.

#76 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/S

#77 Automatic update of dependency pygithub from 1.50 to 1.51
  Pipfile.lock
Labels: bot, size/XS

#78 Automatic update of dependency pylint from 2.5.0 to 2.5.1
  Pipfile.lock
Labels: bot, size/M

#79 Automatic update of dependency pylint from 2.5.1 to 2.5.2
  Pipfile.lock
Labels: bot, size/XS

#80 Automatic update of dependency pytest from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/M

#82 Automatic update of dependency google-api-python-client from 1.8.2 to 1.8.3
  Pipfile.lock
Labels: bot, size/M

#81 Vault is re encrypted with new vault pass
  playbooks/group_vars/all/vault
Labels: approved, size/M

#85 Automatic update of dependency thoth-common from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/L

#86 Automatic update of dependency thoth-common from 0.13.4 to 0.13.3
  Pipfile.lock
Labels: bot, size/XS

#87 Automatic update of dependency thoth-common from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/XS

#88 Automatic update of dependency thoth-common from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/S

#89 Automatic update of dependency thoth-common from 0.13.5 to 0.13.6
  Pipfile.lock
Labels: bot, size/XS

#90 Automatic update of dependency pytest-cov from 2.8.1 to 2.9.0
  Pipfile.lock
Labels: bot, size/XS

#91 Automatic update of dependency google-api-python-client from 1.8.3 to 1.8.4
  Pipfile.lock
Labels: bot, size/XS

#92 Automatic update of dependency thoth-common from 0.13.6 to 0.13.7
  Pipfile.lock
Labels: bot, size/XS

#93 Automatic update of dependency thoth-common from 0.13.7 to 0.13.8
  Pipfile.lock
Labels: bot, size/M
